<?php
/**
 * ContactEnvelopeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Phonebook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phonebook API
 *
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Messente\Phonebook;

/**
 * ContactEnvelopeTest Class Doc Comment
 *
 * @category    Class
 * @description ContactEnvelope
 * @package     Messente\Phonebook
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ContactEnvelopeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactEnvelope"
     */
    public function testContactEnvelope()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }
}
