<?php
/**
 * ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Phonebook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phonebook API
 *
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Messente\Phonebook;

use \Messente\Phonebook\Configuration;
use \Messente\Phonebook\ApiException;
use \Messente\Phonebook\ObjectSerializer;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Messente\Phonebook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addContactToGroup
     *
     * .
     *
     */
    public function testAddContactToGroup()
    {
    }

    /**
     * Test case for createContact
     *
     * .
     *
     */
    public function testCreateContact()
    {
    }

    /**
     * Test case for deleteContact
     *
     * .
     *
     */
    public function testDeleteContact()
    {
    }

    /**
     * Test case for fetchContact
     *
     * .
     *
     */
    public function testFetchContact()
    {
    }

    /**
     * Test case for fetchContactGroups
     *
     * .
     *
     */
    public function testFetchContactGroups()
    {
    }

    /**
     * Test case for fetchContacts
     *
     * .
     *
     */
    public function testFetchContacts()
    {
    }

    /**
     * Test case for removeContactFromGroup
     *
     * .
     *
     */
    public function testRemoveContactFromGroup()
    {
    }

    /**
     * Test case for updateContact
     *
     * .
     *
     */
    public function testUpdateContact()
    {
    }
}
