<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Phonebook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phonebook API
 *
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Messente\Phonebook;

use \Messente\Phonebook\Configuration;
use \Messente\Phonebook\ApiException;
use \Messente\Phonebook\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Messente\Phonebook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createGroup
     *
     * .
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * .
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for fetchGroup
     *
     * .
     *
     */
    public function testFetchGroup()
    {
    }

    /**
     * Test case for fetchGroups
     *
     * .
     *
     */
    public function testFetchGroups()
    {
    }

    /**
     * Test case for updateGroup
     *
     * .
     *
     */
    public function testUpdateGroup()
    {
    }
}
